(cl:defpackage rospy_message_converter-msg
  (:use )
  (:export
   "<NESTEDUINT8ARRAYTESTMESSAGE>"
   "NESTEDUINT8ARRAYTESTMESSAGE"
   "<TESTARRAY>"
   "TESTARRAY"
   "<UINT8ARRAY3TESTMESSAGE>"
   "UINT8ARRAY3TESTMESSAGE"
   "<UINT8ARRAYTESTMESSAGE>"
   "UINT8ARRAYTESTMESSAGE"
  ))

